using System;

namespace QuickCommerce.Core.DTOs.Store
{
    /// <summary>
    /// Response returned after successful enterprise store onboarding.
    /// </summary>
    public class StoreOnboardingResultDto
    {
        // =====================================================
        // STORE
        // =====================================================

        public int StoreId { get; set; }

        public string StoreCode { get; set; } = string.Empty;

        public string StoreName { get; set; } = string.Empty;

        // =====================================================
        // OWNER
        // =====================================================

        public int OwnerUserId { get; set; }

        public string OwnerName { get; set; } = string.Empty;

        public string OwnerMobile { get; set; } = string.Empty;

        public string OwnerEmail { get; set; } = string.Empty;

        // =====================================================
        // LOGIN
        // =====================================================

        /// <summary>
        /// Username used for login.
        /// (Initially Mobile Number)
        /// </summary>
        public string Username { get; set; } = string.Empty;

        /// <summary>
        /// Temporary password generated by system.
        /// User must change after first login.
        /// </summary>
        public string TemporaryPassword { get; set; } = string.Empty;

        // =====================================================
        // ROLE
        // =====================================================

        public string RoleName { get; set; } = "STORE_OWNER";

        // =====================================================
        // STATUS
        // =====================================================

        public bool Success { get; set; }

        public string Message { get; set; } = string.Empty;

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}